import = [
    "~/.config/alacritty/tomorrow_night.toml"
]

[font]
size = 13

[font.bold]
family = "JetBrainsMono"

[font.bold_italic]
family = "JetBrainsMono"

[font.italic]
family = "JetBrainsMono"

[font.normal]
family = "JetBrainsMono"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[window]
opacity = 0.7
