import = [
    "~/.config/alacritty/tomorrow_night.toml"
]

[font]
size = 13
normal      = { family = "JetBrainsMono", style = "Regular" }
bold        = { family = "JetBrainsMono", style = "Bold" }
italic      = { family = "JetBrainsMono", style = "Italic" }
bold_italic = { family = "JetBrainsMono", style = "Bold Italic" }

# Bring up vi mode for pager Control+Shift+Space by default
[keyboard]
bindings = [
    { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" },
    { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
    { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
    { key = "PageUp", mods = "Control|Shift", action = "ScrollPageUp" },
    { key = "PageDown", mods = "Control|Shift", action = "ScrollPageDown" },
    { key = "k", mods = "Control|Shift", action = "ScrollLineUp" },
    { key = "j", mods = "Control|Shift", action = "ScrollLineDown" },
    { key = "Home", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "End", mods = "Control|Shift", action = "ScrollToBottom" },
]

[window]
opacity = 0.7
