#!/bin/bash

# as I lay dying (at 4:33 AM after trying to figure this out for hours)

sleep .05 # need to wait for rofi to exit first -- deadlock?

if [ "$1" = "shutdown" ]; then
	poweroff
elif [ "$1" = "reboot" ]; then
	reboot
elif [ "$1" = "lockscreen" ]; then
	slock
fi
