#!/bin/bash

if [ "$1" = "drun" ]; then
	drun_options=(-show drun)
	drun_options+=(-modes drun)
	drun_options+=(-show-icons)
	drun_options+=(-display-drun )
	drun_options+=(-theme-str 'window { location: center; height: 14%; width: 20%; }')

	rofi "${drun_options[@]}"
elif [ "$1" = "powermenu" ]; then
	pm_options=(-show powermenu)
	pm_options+=(-modes powermenu:/home/dylan/.config/rofi/rofi-power-menu)
	pm_options+=(-theme-str 'inputbar { children: [ prompt,textbox-prompt-colon,case-indicator ]; enabled: false; }')
	pm_options+=(-theme-str "window { location: center; height: 9%; width: 8%; }")

	rofi "${pm_options[@]}"
fi
