#!/bin/bash

# ripped and stripped from https://github.com/jluttine/rofi-power-menu
# probably should have forked

all=(shutdown reboot lockscreen logout)
show=("${all[@]}")

declare -A texts
texts[shutdown]="Shut down"
texts[reboot]="Reboot"
texts[lockscreen]="Lock screen"
texts[logout]="Log out"

declare -A icons
icons[shutdown]="\uf924"
icons[reboot]=""
icons[lockscreen]=""
icons[logout]=""

declare -A actions
actions[shutdown]="systemctl poweroff"
actions[reboot]="systemctl reboot"
actions[lockscreen]="slock"
actions[logout]="loginctl terminate-session ${XDG_SESSION_ID-}"

if [ $# -eq 0 ]; then
	echo -e "\0prompt\x1f"
	for entry in "${show[@]}"; do
		echo -e "${texts[$entry]}\0icon\x1fpower"
	done
else
	for entry in "${show[@]}"; do
		if [ "$1" = "${texts[$entry]}" ]; then
			${actions[$entry]}
		fi
	done
	echo "Errruuuggghhh"
fi
