#!/bin/bash

# ripped and stripped from https://github.com/jluttine/rofi-power-menu
# probably should have forked

all=(shutdown reboot lockscreen)
show=("${all[@]}")

declare -A texts
texts[shutdown]=" shut down"
texts[reboot]=" reboot"
texts[lockscreen]=" lock screen"

declare -A actions
actions[shutdown]="/usr/bin/poweroff"
actions[reboot]="/usr/bin/reboot"
actions[lockscreen]="slock"

if [ $# -eq 0 ]; then
	echo -e "\0prompt\x1f"
	for entry in "${show[@]}"; do
		echo -e "${texts[$entry]}"
	done
else
	for entry in "${show[@]}"; do
		if [ "$1" = "${texts[$entry]}" ]; then
			#loginctl terminate-session ${XDG_SESSION_ID-}
			${actions[$entry]}
		fi
	done
fi
