#!/bin/bash

# ripped and stripped from https://github.com/jluttine/rofi-power-menu
# probably should have forked

all=(shutdown reboot lockscreen logout)
show=("${all[@]}")

declare -A texts
texts[shutdown]=" shut down"
texts[reboot]=" reboot"
texts[lockscreen]=" lock screen"

declare -A icons
icons[shutdown]="\uf924"
icons[reboot]=""
icons[lockscreen]=""

declare -A actions
actions[shutdown]="systemctl poweroff"
actions[reboot]="systemctl reboot"
actions[lockscreen]="slock"

if [ $# -eq 0 ]; then
	echo -e "\0prompt\x1f"
	for entry in "${show[@]}"; do
		echo -e "${texts[$entry]}"
	done
else
	for entry in "${show[@]}"; do
		if [ "$1" = "${texts[$entry]}" ]; then
			${actions[$entry]}
		fi
	done
	echo "Errruuuggghhh"
fi
