# if not running interactively, don't do anything
[[ $- != *i* ]] && return

BOLD=$(tput bold)         # bold
RESET=$(tput sgr0)        # turn off all attributes
PRIMARY=$(tput setaf 4)   # light blue
SECONDARY=$(tput setaf 7) # white
PS1='\[$BOLD\]\[$PRIMARY\]\u@\h\[$SECONDARY\] \w \$\[$RESET\] '

set -o vi
bind '"jk":"\el"'
bind -m vi-command '"v": ""'

export VISUAL=vim
export EDITOR="$VISUAL"
export LESSHISTFILE=-

source /usr/share/bash-completion/bash_completion

alias ls='ls --color=auto'
alias la='ls -A'
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias lock='slock'
