#!/bin/bash

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config window_gap          10
bspc config automatic_scheme    alternate
bspc config single_monocle		true # set to monocle layout if only one window
bspc config borderless_monocle	true # then won't see the default grey outline for focused window
bspc config gapless_monocle		true # no capes (gaps)

bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pavucontrol state=floating

picom -b
~/dotfiles/wallpaper/fehbg &
~/.config/polybar/launch.sh
