#!/bin/bash

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &
vmware-user-suid-wrapper

xrandr --output Virtual1 --mode 2560x1440
picom -b
~/.config/fehbg &

# get names of connected monitors
# bspc query -M --names
bspc monitor -d 1 2 3 4 5 6 7

bspc config window_gap           5

bspc config border_width         2
bspc config normal_border_color  "#131212"
bspc config focused_border_color "#81a2be"

bspc config automatic_scheme     alternate

bspc config single_monocle		 true # set to monocle layout if only one window
bspc config borderless_monocle	 true # then won't see the default grey outline for focused window
bspc config gapless_monocle		 true # no capes (gaps)

# scratchpad one
bspc rule -a scratchpad1 sticky=on state=floating hidden=on center=true rectangle=1500x600+0+0
~/.config/bspwm/start_scratch.sh 1

# scratchpad two
bspc rule -a scratchpad2 sticky=on state=floating hidden=on rectangle=1500x600+0+0
~/.config/bspwm/start_scratch.sh 2

bspc rule -a rdesktop state=floating center=true rectangle=800x800+0+0
