#!/bin/bash

# ripped and stripped from https://github.com/jluttine/rofi-power-menu
# probably should have forked

all=(shutdown reboot lockscreen)
show=("${all[@]}")

declare -A texts
texts[shutdown]=" shut down"
texts[reboot]=" reboot"
texts[lockscreen]=" lock screen"

ineedtosleep="/home/dylan/.config/rofi/ineedtosleep"

if [ $# -eq 0 ]; then
	echo -e "\0prompt\x1f"
	for entry in "${show[@]}"; do
		echo -e "${texts[$entry]}"
	done
else
	for entry in "${show[@]}"; do
		if [ "$1" = "${texts[$entry]}" ]; then
			coproc ( $ineedtosleep $entry )
		fi
	done
fi
